version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.1
    steps:
      - checkout
      - run:
          name: System Information
          command: |
            pwd
            ls -la
            echo "node: $(node -v)"
            echo "npm: $(npm -v)"
            echo "yarn $(yarn -v)"
      - run:
          name: Build
          command: npm run build
      - run:
          name: Deploy
          command: |
            pwd
            ls -la
            echo "node: $(node -v)"
            echo "npm: $(npm -v)"
            echo "yarn $(yarn -v)"
